# Generated by Django 4.2.7 on 2024-02-07 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tiempo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transacciontiempo",
            name="propietario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="propietario_cuenta",
                to="tiempo.cuenta",
            ),
        ),
        migrations.AlterField(
            model_name="transacciontiempo",
            name="demandante",
            field=models.ManyToManyField(
                related_name="transacciones_demandante", to="tiempo.usuario"
            ),
        ),
        migrations.AlterField(
            model_name="transacciontiempo",
            name="demandanteCuenta",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="tiempo.cuenta",
                verbose_name="quien oferta del servicio",
            ),
        ),
        migrations.AlterField(
            model_name="transacciontiempo",
            name="numero_minutos",
            field=models.IntegerField(blank=True, null=True, verbose_name="Minutos"),
        ),
        migrations.AlterField(
            model_name="transacciontiempo",
            name="servicio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="tiempo.servicio"
            ),
        ),
    ]
