# Generated by Django 4.2.7 on 2023-12-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tiempo", "0002_persona_password_confirmation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="persona",
            old_name="password_confirmation",
            new_name="confirm_password",
        ),
    ]
