# Generated by Django 4.2.6 on 2023-12-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiempo", "0004_alter_servicio_estadovigencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicio",
            name="fecha_creacion",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Creación"
            ),
        ),
        migrations.AlterField(
            model_name="servicio",
            name="fecha_vigente",
            field=models.DateField(blank=True, null=True, verbose_name="Fecha Vigente"),
        ),
    ]
